# add the linters you want stickler to use for this project
linters:
  eslint:
    # indicate where is the config file for stylelint
    config: './.eslintrc.json'
files:
  ignore:
      - 'src/serviceWorker.js'

# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config

# find full documentation here: https://stickler-ci.com/docs
